Attendance, Absence and Avg Check-in-time Reports
BC-MAY-21-ROR/kata-07-reloj-checador-k7-n21-t2 pull request #26
Opened 2022-01-28 22:23 UTC by corps01

# Description
WHAT:
-Implemented reports controller to generate reports based on Employee, Attendances and Absences models
-Created views for each report alongside their SASS stylesheet.
-Created partial sidebar to access reports

2022-01-28 22:48 UTC, JuanequeX requested changes

2022-01-28 22:48 UTC, JuanequeX commented on checkClock/app/assets/stylesheets/reports.scss
> +
Change this identation at 2 spaces, please

2022-01-28 22:48 UTC, JuanequeX commented on checkClock/app/assets/stylesheets/reports.scss
> +  }
Add a blank line here

2022-01-28 22:48 UTC, JuanequeX commented on checkClock/app/controllers/reports_controller.rb
> +
possibly in your VS code, you have the system to identation configurate it at 4 spaces, please configure it to 2 spaces to solve this identations

2022-01-28 22:48 UTC, JuanequeX commented on checkClock/app/controllers/reports_controller.rb
> +end
Add a blank line here

2022-01-28 22:48 UTC, JuanequeX commented on checkClock/app/views/application/_sidebar.erb
> +  </nav>
Add a blank line here

2022-01-28 22:48 UTC, JuanequeX commented on checkClock/app/views/application/_sidebar.erb
> +    </div>
Same here, check your identation

2022-01-28 22:48 UTC, JuanequeX commented on checkClock/app/views/reports/absences.erb
> +<% end %>
Add a blank line hera and review this identation

2022-01-28 23:29 UTC, JuanequeX approved these changes
LGTM

2022-01-29 04:58 UTC, dany-herz42 approved these changes

2022-01-29 04:59 UTC, merged